# Generated by Django 5.2.8 on 2025-11-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item', 'size')},
        ),
    ]
