# Generated by Django 5.2.8 on 2025-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
