# Generated by Django 5.2.7 on 2025-10-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0002_remove_item_quantity_remove_item_sku_item_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
