# Generated by Django 5.2.8 on 2025-11-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0003_order_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
