# Generated by Django 5.2.7 on 2025-11-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
    ]
