# Generated by Django 5.2.7 on 2025-11-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
