# Generated by Django 5.2.7 on 2025-11-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0004_item_slug_order_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
