# Generated by Django 5.2.8 on 2025-11-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0004_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='The customer-facing code (e.g., WELCOME10)', max_length=50, unique=True)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls if this code is active in Stripe')),
                ('stripe_coupon_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('stripe_promo_id', models.CharField(blank=True, editable=False, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
