# Generated by Django 5.2.7 on 2025-11-10 01:18

from django.db import migrations

def gen_slugs(apps, schema_editor):
    Item = apps.get_model('kickhub', 'Item')
    for it in Item.objects.all().iterator():
        if not it.slug:
            # trigger your model's save() which generates a unique slug
            it.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0004_item_slug'),
    ]

    operations = [
        migrations.RunPython(gen_slugs, migrations.RunPython.noop),
    ]
