# Generated by Django 5.2.7 on 2025-11-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0005_shoppingcart_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
