# Generated by Django 5.2.7 on 2025-11-10 01:25

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Item = apps.get_model('kickhub', 'Item')

    def unique_slug(base, pk):
        slug = base or f"item-{pk}"
        n = 2
        # ensure uniqueness across table
        while Item.objects.filter(slug=slug).exclude(pk=pk).exists():
            slug = f"{base}-{n}"
            n += 1
        return slug

    # Fill NULL or empty slugs
    for it in Item.objects.filter(slug__isnull=True) | Item.objects.filter(slug="") | Item.objects.filter(slug=" "):
        base = slugify(f"{(it.brand or '').strip()} {(it.model or '').strip()}") \
               or slugify((it.description or '')[:50]) \
               or f"item-{it.pk}"
        it.slug = unique_slug(base, it.pk)
        it.save(update_fields=["slug"])

class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0005_populate_item_slugs'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
