# Generated by Django 5.2.7 on 2025-11-14 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0006_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='kickhub.sizes'),
            preserve_default=False,
        ),
    ]
