# Generated by Django 5.2.7 on 2025-11-14 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickhub', '0007_cartitem_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='kickhub.sizes'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'item', 'size')},
        ),
    ]
